// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWUu0IE_rhEngk0KA7n6vpF1i70VIyfw',
    appId: '1:656315214068:web:02baf19564d290378a96a1',
    messagingSenderId: '656315214068',
    projectId: 'ezcharge-380ad',
    authDomain: 'ezcharge-380ad.firebaseapp.com',
    storageBucket: 'ezcharge-380ad.firebasestorage.app',
    measurementId: 'G-HRTMHLSEFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVcOCM0W6fy3CL4ujBdKST3GwdCHTmc0',
    appId: '1:656315214068:android:9b770028ec4323b18a96a1',
    messagingSenderId: '656315214068',
    projectId: 'ezcharge-380ad',
    storageBucket: 'ezcharge-380ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBiJWpvznd0riFN-8i8x0RsBUioDIkWA',
    appId: '1:656315214068:ios:a3c765c3cde07af18a96a1',
    messagingSenderId: '656315214068',
    projectId: 'ezcharge-380ad',
    storageBucket: 'ezcharge-380ad.firebasestorage.app',
    iosBundleId: 'com.example.smartev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcBiJWpvznd0riFN-8i8x0RsBUioDIkWA',
    appId: '1:656315214068:ios:a3c765c3cde07af18a96a1',
    messagingSenderId: '656315214068',
    projectId: 'ezcharge-380ad',
    storageBucket: 'ezcharge-380ad.firebasestorage.app',
    iosBundleId: 'com.example.smartev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkWUu0IE_rhEngk0KA7n6vpF1i70VIyfw',
    appId: '1:656315214068:web:981af483ff6fc4988a96a1',
    messagingSenderId: '656315214068',
    projectId: 'ezcharge-380ad',
    authDomain: 'ezcharge-380ad.firebaseapp.com',
    storageBucket: 'ezcharge-380ad.firebasestorage.app',
    measurementId: 'G-WHVH13QP3E',
  );
}
